Lan = "EN"
"设置界面" = "Setting"
"使用卫月日志" = "Enable Dalamud log"
"扫描热键栏" = "Scan Hotbar"
"扫描宏" = "Scan Macro"
"寻路相关数据可视化" = "Pathfinding Visual"
"清除" = "Clear"
"用户工具" = "User Tool"
"启用Debug日志" = "Enable Debug log"
"打开日志文件夹" = "Open log folder"
"模拟输入等级 :" = "Input simulation level"
"防T(挂机操作用)" = "AntiAfk"
"Update间隔越低,插件表现越好,cpu消耗越高.有个i5就可以拉满" = "Lower UpdateInterval,Higher Cpu usage."
"Update间隔 (ms): " = "UpdateInterval (ms):"
"寻路服务器Url:" = "PathfindingServerUrl:"
"QQ群:" = "QQ Group (CN): "
"当前ACR:" = "Curr ACR:"
"Dot黑名单" = "Dot blacklist"
"快捷键" = "Hotkey"
"宏" = "Macro"
"ACR偏好" = "ACR Prefer"
"目标濒死检测" = "TTK"
"通用TTK机制检测时间" = "General TTK Time"
"最终爆发TTK检测时间" = "FinalBurst TTK Time"
"保存设置" = "Save Setting"
"自动重置" = "AutoReset"
"重新加载时间轴" = "Reload Triggerlines"
"强制加载" = "Force load"
"打开时间轴编辑器" = "Open Editor"
"当前场景可用时间轴" = "Avaliable triggerlines for Terr"
"打开时间轴文件夹" = "Open Triggerline Folder"
"导入Cactbot时间轴" = "Import data from Cactbot timeline"
"转换" = "Convert"
"将Cactbot时间轴粘贴到此处" = "Paste Cactbot timeline here"
"确认" = "Confirm"
"重命名" = "Rename"
"秒 用 " = " Cast "
"指定时间轴(不自动切换) : " = "Specify triggerline: (auto switch off): "
"清除并自动切换一次" = "Clear and auto switch once"
"指定加载" = "Load"
"使用技能" = "CastSpell"
"关闭其他组" = "DisableOtherGroup"
"锁定技能" = "LockSpell"
"重新用起手" = "ReplayOpener"
"切换目标" = "SelectTarget"
"设置面向" = "SetRotation"
"技能队列" = "SpellQueue"
"切换AOE" = "SwitchAOE"
"切换爆发" = "SwitchBurst"
"切换最终爆发" = "SwitchFinalBurst"
"切换DOT" = "SwitchDOT"
"切换自动攻击" = "SwitchPull"
"使用爆发药" = "UsePotion"
"战斗开始后多少秒" = "AfterBattleStart"
"另一组触发后" = "AfterOtherGroup"
"buff小于多少秒" = "Buff left time less than X(s)"
"检测技能CD" = "CheckSpellCD"
"起手倒计时剩余多少ms" = "CountDownInOpener (ms)"
"敌人读条使用技能" = "EnemyCastSpell"
"目标血量百分比 (通过名字或者Id)" = "TargetHpPct (by name/id)"
"目标血量百分比 (通过类型)" = "TargetHpPct (by targetType)"
"敌人存在于视野中" = "EnemyIsLOS"
"敌人TTK (几秒内死亡)" = "EnemyTimeToKill (s)"
"聊天监控" = "ChatListener"
"在目标血量百分比 (通过类型)中,无法配置TargetType为Location/DefaultByCode/SpecifyTarget " = "In 'TargetHpPct (by targetType)',you cant set the targetType to Location/DefaultByCode/SpecifyTarget "
"身位指示器设置:" = "MeleePosHelper:"
"侧面:" = "Flank:"
"背面:" = "Behind:"
"启用" = "Enable"
"天气变化" = "OnWeatherChange"
"当前天气Id" = "CurrWeatherId"
"左键选中以打开节点编辑UI,右键单击以打开二级菜单" = "Ops: LeftClick to show the editor /RightClick to show the popup"
"行为" = "Action"
"条件" = "Condition"
"立即检测" = "CheckNow"
"等待条件" = "Wait4Condition"
"延迟[秒]" = "Delay[Sec]"
"多次执行" = "MultiTimes"
"并行" = "Parallel"
"序列" = "Sequence"
"选择" = "Select"
"删除" = "Delete"
"上移" = "Up"
"下移" = "Down"
"复制" = "Copy"
"粘贴" = "Paste"
"导出变量:" = "ExposedVars:"